### ISSUE TITLE
updates?

### ISSUE THREAD

**Issue by daniilfigasystems** [devos50/qemu#166]
When new updates?

**Comment by devos50** [comment]
I haven't planned to work on anything concrete but maybe I'll spend a few days here and there during summer on getting some components working (preferably USB communication).

**Comment by daniilfigasystems** [comment]
> I haven't planned to work on anything concrete but maybe I'll spend a few days here and there during summer on getting some components working (preferably USB communication).

Thank you for supporting this project. Firstly, i thought that you abandoned this project.

**Comment by gdandsm64fan123** [comment]
hey there devos, remember me? its been a while (1 year exactly) since i was watching a MattKC video i remembered this so i decided to come back here to see how much progress you made. Now i wanna say something: Now i have a proper Linux enviroment so i can now potentially get the thing compiled!
that is until i got an error. check #212 for more abt it
