### ISSUE TITLE
How long until iPod Touch 2G is up and running?

### ISSUE THREAD

**Issue by zoe-vb** [devos50/qemu#24]
Just wondering if you have an idea as to how long it'll be until the ipod touch 2g is functional in qemu- I expect this is a harder task than the 1G due to apple starting to add extra restrictions by this time.

**Comment by devos50** [comment]
Hmm that's hard to answer. I'm currently working to get iBoot fully operational and running. I could re-use a lot of peripheral code that I already made for the iPod Touch 1G, but it looks like the iPod Touch 2G is using a completely different Flash Memory Controller and Display Controller. These might take quite some time to get right. Fortunately, I do have raw source code of the Display Controller so that should speed up the process.

I didn't encounter much issues due to the additional security measures. One aspect that took a bit more time than anticipated is that Apple started using the IMG3 format for binary images. To correctly validate the signature and keys, I had to get the PKI engine up and running. But that component now seems to be fully functional.

I try to spend an evening here and there on making progress with this. Note that you can also follow my progress [here](https://github.com/devos50/qemu/tree/ipod_touch_2g).

**Comment by upintheairsheep** [comment]
Is iOS 2 and 3 functional

**Comment by devos50** [comment]
@upintheairsheep no it's not as I'm still working on getting the bootloader functional (the software that loads iOS).

**Comment by upintheairsheep** [comment]
> @upintheairsheep no it's not as I'm still working on getting the bootloader functional (the software that loads iOS).

I meant on the iPod Touch original
