### ISSUE TITLE
why the first exec code is from IBOOT_BASE not from VROM_MEM_BASE?

### ISSUE THREAD

**Issue by iOSPrincekin** [devos50/qemu#44]
Hi:
    I learn [qemu-ios](https://github.com/devos50/qemu-ios) project, I find this code in the ipod_touch.c file:

`
static void ipod_touch_cpu_reset(void *opaque)
{
    IPodTouchMachineState *nms = IPOD_TOUCH_MACHINE((MachineState *)opaque);
    ARMCPU *cpu = nms->cpu;
    CPUState *cs = CPU(cpu);

    cpu_reset(cs);

    //env->regs[0] = nms->kbootargs_pa;
    //cpu_set_pc(CPU(cpu), 0xc00607ec);
    cpu_set_pc(CPU(cpu), IBOOT_BASE);
    //env->regs[0] = 0x9000000;
    //cpu_set_pc(CPU(cpu), LLB_BASE + 0x100);
    //cpu_set_pc(CPU(cpu), VROM_MEM_BASE);
}

`

from that code I guess the first code is from IBOOT_BASE not from VROM_MEM_BASE, in my memory, the first exec code should be from VROM_MEM_BASE according below figure, it makes me confused, can you explain it? thanks a lot!

<img width="468" alt="image-113" src="https://github.com/devos50/qemu-ios/assets/40560744/efb29522-04dd-41de-8ea1-e9213687a895">

**Comment by devos50** [comment]
That is a good question! I indeed load the bottom at `VROM_MEM_BASE` but I couldn't get the bootrom/llb up and running, due to some missing code related to the 8900 decryption logic. Instead, I skip initialisation of the bootrom/llb (as they just initialise some peripherals) and load iBoot directly.

I'm currently working on simulating the iPod Touch 2G and for that device I do have the entire boot chain, up to the kernel, functional.

**Comment by iOSPrincekin** [comment]
nice! I'm very much on the arrival of the iPod Touch 2G

**Comment by devos50** [comment]
@iOSPrincekin iPod Touch 2G support is here now 👍
